/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    articles: Article;
    companies: Company;
    vacancies: Vacancy;
    applications: Application;
    categories: Category;
    tags: Tag;
    authors: Author;
    images: Image;
    files: File;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    vacancies: VacanciesSelect<false> | VacanciesSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    images: ImagesSelect<false> | ImagesSelect<true>;
    files: FilesSelect<false> | FilesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: string;
  /**
   * scientific | news | reference. Controls which public index it appears under.
   */
  kind: 'scientific' | 'news' | 'reference';
  title: string;
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (string | null) | Image;
  author?: (string | null) | Author;
  category?: (string | null) | Category;
  tags?: (string | Tag)[] | null;
  /**
   * Nullable until published; defaults to now on publish.
   */
  publishedAt?: string | null;
  /**
   * Derived, optional.
   */
  readingTimeMinutes?: number | null;
  /**
   * Falls back to title (rendered in Session 06).
   */
  metaTitle?: string | null;
  /**
   * Falls back to excerpt (rendered in Session 06).
   */
  metaDescription?: string | null;
  /**
   * Falls back to hero image, then site default (Session 06).
   */
  ogImage?: (string | null) | Image;
  /**
   * Content locale (PRD §4.1). ar = RTL default, en = LTR.
   */
  locale: 'ar' | 'en';
  /**
   * Shared UUID linking this item to its translations in other locales (PRD §6, OQ-3 default).
   */
  translationGroupId: string;
  /**
   * Unique within (type, locale); lowercase, hyphenated; Arabic transliterated to ASCII (PRD §6.9, OQ-14).
   */
  slug: string;
  /**
   * draft → published → archived (PRD §7.3).
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * Exact old absolute URL; populated by Session 07; used to build the 301 map.
   */
  legacyUrl?: string | null;
  /**
   * Feature this item on the Home page (this locale only).
   */
  featured?: boolean | null;
  /**
   * Order within the featured set (lower shows first).
   */
  featuredOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "images".
 */
export interface Image {
  id: string;
  /**
   * Arabic alt text. Required to publish an ar item using this image (PRD §8.4).
   */
  altTextAr?: string | null;
  /**
   * English alt text. Required to publish an en item using this image (PRD §8.4).
   */
  altTextEn?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: string;
  name: string;
  bio?: string | null;
  avatar?: (string | null) | Image;
  /**
   * Content locale (PRD §4.1). ar = RTL default, en = LTR.
   */
  locale: 'ar' | 'en';
  /**
   * Shared UUID linking this item to its translations in other locales (PRD §6, OQ-3 default).
   */
  translationGroupId: string;
  /**
   * Unique within (type, locale); lowercase, hyphenated; Arabic transliterated to ASCII (PRD §6.9, OQ-14).
   */
  slug: string;
  /**
   * draft → published → archived (PRD §7.3).
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * Exact old absolute URL; populated by Session 07; used to build the 301 map.
   */
  legacyUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  /**
   * Parent category (enables nesting). Null for a top-level category.
   */
  parent?: (string | null) | Category;
  /**
   * Falls back to title (rendered in Session 06).
   */
  metaTitle?: string | null;
  /**
   * Falls back to excerpt (rendered in Session 06).
   */
  metaDescription?: string | null;
  /**
   * Falls back to hero image, then site default (Session 06).
   */
  ogImage?: (string | null) | Image;
  /**
   * Content locale (PRD §4.1). ar = RTL default, en = LTR.
   */
  locale: 'ar' | 'en';
  /**
   * Shared UUID linking this item to its translations in other locales (PRD §6, OQ-3 default).
   */
  translationGroupId: string;
  /**
   * Unique within (type, locale); lowercase, hyphenated; Arabic transliterated to ASCII (PRD §6.9, OQ-14).
   */
  slug: string;
  /**
   * draft → published → archived (PRD §7.3).
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * Exact old absolute URL; populated by Session 07; used to build the 301 map.
   */
  legacyUrl?: string | null;
  /**
   * Feature this item on the Home page (this locale only).
   */
  featured?: boolean | null;
  /**
   * Order within the featured set (lower shows first).
   */
  featuredOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  name: string;
  /**
   * Content locale (PRD §4.1). ar = RTL default, en = LTR.
   */
  locale: 'ar' | 'en';
  /**
   * Shared UUID linking this item to its translations in other locales (PRD §6, OQ-3 default).
   */
  translationGroupId: string;
  /**
   * Unique within (type, locale); lowercase, hyphenated; Arabic transliterated to ASCII (PRD §6.9, OQ-14).
   */
  slug: string;
  /**
   * draft → published → archived (PRD §7.3).
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * Exact old absolute URL; populated by Session 07; used to build the 301 map.
   */
  legacyUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: string;
  name: string;
  logo?: (string | null) | Image;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  externalUrl?: string | null;
  founded?: string | null;
  headquarters?: string | null;
  /**
   * Falls back to title (rendered in Session 06).
   */
  metaTitle?: string | null;
  /**
   * Falls back to excerpt (rendered in Session 06).
   */
  metaDescription?: string | null;
  /**
   * Falls back to hero image, then site default (Session 06).
   */
  ogImage?: (string | null) | Image;
  /**
   * Content locale (PRD §4.1). ar = RTL default, en = LTR.
   */
  locale: 'ar' | 'en';
  /**
   * Shared UUID linking this item to its translations in other locales (PRD §6, OQ-3 default).
   */
  translationGroupId: string;
  /**
   * Unique within (type, locale); lowercase, hyphenated; Arabic transliterated to ASCII (PRD §6.9, OQ-14).
   */
  slug: string;
  /**
   * draft → published → archived (PRD §7.3).
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * Exact old absolute URL; populated by Session 07; used to build the 301 map.
   */
  legacyUrl?: string | null;
  /**
   * Feature this item on the Home page (this locale only).
   */
  featured?: boolean | null;
  /**
   * Order within the featured set (lower shows first).
   */
  featuredOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vacancies".
 */
export interface Vacancy {
  id: string;
  title: string;
  employer?: string | null;
  country: 'egypt' | 'emirates' | 'ksa' | 'kuwait' | 'north_africa' | 'general';
  /**
   * OQ-13 may extend.
   */
  roleType: 'medical_representative' | 'product_specialist' | 'territory_manager' | 'other';
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  requirements?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  location?: string | null;
  applyEmail?: string | null;
  applyWhatsapp?: string | null;
  postedAt: string;
  expiresAt?: string | null;
  /**
   * Derived: true when expires_at is null or in the future.
   */
  isActive?: boolean | null;
  /**
   * Falls back to title (rendered in Session 06).
   */
  metaTitle?: string | null;
  /**
   * Falls back to excerpt (rendered in Session 06).
   */
  metaDescription?: string | null;
  /**
   * Falls back to hero image, then site default (Session 06).
   */
  ogImage?: (string | null) | Image;
  /**
   * Content locale (PRD §4.1). ar = RTL default, en = LTR.
   */
  locale: 'ar' | 'en';
  /**
   * Shared UUID linking this item to its translations in other locales (PRD §6, OQ-3 default).
   */
  translationGroupId: string;
  /**
   * Unique within (type, locale); lowercase, hyphenated; Arabic transliterated to ASCII (PRD §6.9, OQ-14).
   */
  slug: string;
  /**
   * draft → published → archived (PRD §7.3).
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * Exact old absolute URL; populated by Session 07; used to build the 301 map.
   */
  legacyUrl?: string | null;
  /**
   * Feature this item on the Home page (this locale only).
   */
  featured?: boolean | null;
  /**
   * Order within the featured set (lower shows first).
   */
  featuredOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: string;
  vacancy?: (string | null) | Vacancy;
  applicantName?: string | null;
  applicantEmail?: string | null;
  applicantPhone?: string | null;
  cvFile?: (string | null) | File;
  consentGiven?: boolean | null;
  sourceLocale?: ('ar' | 'en') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files".
 */
export interface File {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  roles: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'articles';
        value: string | Article;
      } | null)
    | ({
        relationTo: 'companies';
        value: string | Company;
      } | null)
    | ({
        relationTo: 'vacancies';
        value: string | Vacancy;
      } | null)
    | ({
        relationTo: 'applications';
        value: string | Application;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'authors';
        value: string | Author;
      } | null)
    | ({
        relationTo: 'images';
        value: string | Image;
      } | null)
    | ({
        relationTo: 'files';
        value: string | File;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  kind?: T;
  title?: T;
  excerpt?: T;
  body?: T;
  heroImage?: T;
  author?: T;
  category?: T;
  tags?: T;
  publishedAt?: T;
  readingTimeMinutes?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  locale?: T;
  translationGroupId?: T;
  slug?: T;
  status?: T;
  legacyUrl?: T;
  featured?: T;
  featuredOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  body?: T;
  externalUrl?: T;
  founded?: T;
  headquarters?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  locale?: T;
  translationGroupId?: T;
  slug?: T;
  status?: T;
  legacyUrl?: T;
  featured?: T;
  featuredOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vacancies_select".
 */
export interface VacanciesSelect<T extends boolean = true> {
  title?: T;
  employer?: T;
  country?: T;
  roleType?: T;
  description?: T;
  requirements?: T;
  location?: T;
  applyEmail?: T;
  applyWhatsapp?: T;
  postedAt?: T;
  expiresAt?: T;
  isActive?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  locale?: T;
  translationGroupId?: T;
  slug?: T;
  status?: T;
  legacyUrl?: T;
  featured?: T;
  featuredOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  vacancy?: T;
  applicantName?: T;
  applicantEmail?: T;
  applicantPhone?: T;
  cvFile?: T;
  consentGiven?: T;
  sourceLocale?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  parent?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  locale?: T;
  translationGroupId?: T;
  slug?: T;
  status?: T;
  legacyUrl?: T;
  featured?: T;
  featuredOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  locale?: T;
  translationGroupId?: T;
  slug?: T;
  status?: T;
  legacyUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  bio?: T;
  avatar?: T;
  locale?: T;
  translationGroupId?: T;
  slug?: T;
  status?: T;
  legacyUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "images_select".
 */
export interface ImagesSelect<T extends boolean = true> {
  altTextAr?: T;
  altTextEn?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files_select".
 */
export interface FilesSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}